version: "3"

networks:
    laravel:

services:
    site:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        tty: true
        volumes: 
            - ./:/var/www/html
        ports:
            - '80:80'
        depends_on: 
            - php
        networks: 
            - laravel

    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        tty: true
        volumes: 
            - ./:/var/www/html
        ports: 
            - '9000:9000'
        networks: 
            - laravel

    mysql:
        image: mysql:5.7.29
        restart: unless-stopped
        tty: true
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        restart: unless-stopped
        networks:
            - laravel
        #ports:
        #  - '6379:6379'
        
    npm:
        image: node:14
        working_dir: /var/www/html
        entrypoint: ["npm"]
        tty: true
        volumes:
            - ./:/var/www/html
        
        
    app:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            - PMA_ARBITRARY=1
        links:
            - mysql
        ports:
            - 8085:80
        volumes:
            - /sessions
        networks:
            - laravel